FROM  --platform=linux/amd64 python:3.10-bookworm as base
WORKDIR /backend

COPY . /backend

RUN pip install poetry

RUN poetry lock
RUN poetry install
CMD poetry run uvicorn app.router:app --host 0.0.0.0 --port 5000 --reload
