FROM  --platform=linux/amd64 python:3.10-bookworm as requirements-stage

WORKDIR /tmp

RUN pip install poetry==1.6.1

COPY ./pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM --platform=linux/amd64 python:3.10-bookworm

WORKDIR /backend

COPY --from=requirements-stage /tmp/requirements.txt /backend/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /backend/requirements.txt

COPY . /backend

CMD ["uvicorn", "app.router:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
