FROM python:3.12-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /backend
COPY . /backend

RUN uv sync --frozen

CMD ["uv", "run", "fastapi", "run", "router.py","--host", "0.0.0.0", "--port", "5000", "--reload"]
