[theme]
primaryColor="#8be9fd"
backgroundColor="#0E0D11"
secondaryBackgroundColor="#131317"
textColor="#FFF"
font="sans serif"
[browser]
gatherUsageStats = false
[server]
enableXsrfProtection = false
enableCORS = false
